resource/dashboardgroup: Handle updates with mirrors correctly
splunk-terraform/terraform-provider-signalfx pull request #319
Opened 2021-09-27 15:53 UTC by asuresh4

The Terraform provider does not track non-mirrored dashboards in dashboard groups. It keeps track dashboardgroup membership on the respective dashboards. However, the backend modifies dashboard groups object to hold a list of all dashboards it holds, both mirrored and non-mirrored. The API expects this full list of dashboards whenever mirrored dashboards are added/present. Collect all non-mirrored dashboards from the backend and append it to the list of dashboards. This behavior is noted in step 4 of the API docs [here](https://dev.splunk.com/observability/docs/chartsdashboards/dashboard_groups_overview#Add-the-mirrored-dashboard). 

Currently, it does not seem possible to track info about dashboard membership on dashboard group resources with Terraform state as that will introduce a cyclic dependency. The API requires a dashboard group ID for dashboards, so the the dashboard group will need to be created before the member dashboards themselves. As a workaround, this PR attempts to fix the issue by doing a get on the dashboard group to collect all member dashboard ids and append it to list of dashboards with every update request. For this to work as expected it will also be required to set `-parallelism=1` .

Fixes #264

2021-09-27 19:20 UTC, dloucasfx commented
@asuresh4 the fix LGTM , especially from the use case the bug is trying to address. 
my only concern with this approach is that we are not saving the the non-mirrored dashboard in the terraform dashboard group state ; would it create unwanted results if the group was updated outside the terraform? update/add/remove dashboards?

2021-09-27 19:50 UTC, asuresh4 commented
Thanks for taking a look @dloucasfx ! Given that this update introduces a get of the dashboard group before an update, I believe the provider will end up with the latest dashboard group object from the backend, especially the list of dashboards since that's the only value we're interested in under the assumption one does not try to apply changes via Terraform and almost simultaneously make manual updates. In that case, there could be a race condition and the get call may not have the latest values. Were you able to think of any other scenario this could be problematic?

2021-10-06 18:55 UTC, dloucasfx requested changes
Other then this one comment about `HasChange`, the new logic to detect what mirrored dashboards looks solid!

2021-10-06 18:55 UTC, dloucasfx commented on signalfx/resource_signalfx_dashboard_group.go
> +	oldDashboardList, newDashboardList := d.GetChange("dashboard")
````
// GetChange returns the old and new value for a given key.
//
// HasChange should be used to check if a change exists. It is possible
// that both the old and new value are the same if the old value was not
// set and the new value is. This is common, for example, for boolean
// fields which have a zero value of false.
````
Do you want to use `HasChange` to short circuit the call here?

2021-10-08 19:01 UTC, asuresh4 commented on signalfx/resource_signalfx_dashboard_group.go
> +	oldDashboardList, newDashboardList := d.GetChange("dashboard")
Done

2021-10-08 19:07 UTC, merged