Change `rules` from Set to List in detector resource
splunk-terraform/terraform-provider-signalfx pull request #378
Opened 2022-06-10 18:27 UTC by bohdanborovskyi-ma

We've faced a several issues when started migrating hundreds of existing detectors into Terraform due to `rule` being Set.

1. We can't ignore only changes in specific attributes of the `rule`, but rule block as a whole.
Taking into account that any threshold change introduced via SignalFX UI or API would diverge the `description` attribute of modified rule to some autogenerated text, it became very hard to keep our Terraform states with 0 drifts.
At the end we're used to completely ignore changes in the `rule` block, effectively loosing the possibility to modify other rule attributes from within Terraform code.

2. Another downside of TypeSet is that Terraform plan outputs always show re-creation of all rule objects instead of showing actual diff. 
For example, if I have 3 rules and wants to change the `disabled` attribute in one of them - TF plan would show that all old rules should be removed and 3 new ones would be added as it can't match old Set items with new ones.

P.s. I've built the provider locally & tested it on several existing detectors & internal modules without any compatibility issues noticed.
Please let me know if there're some technical constrains to merge this change

2022-06-17 23:48 UTC, bohdanborovskyi-ma commented
@keitwb @mbojko-signalfx Could you please share your feedback on proposed change?

Described downsides of `Set` type severely impact the flexibility & usage convenience for any module which creates detector resources under the hood

2022-07-01 12:53 UTC, mbojko-signalfx commented
Proposed change seems to be reasonable, I'll need to run few test to see if it doesn't introduce backward compatibility issues.

2022-07-20 10:42 UTC, mbojko-signalfx commented
I've had time to verify the proposed change and unfortunately I've noticed backward compatibility issues. 
Changing from `Set` to `List` introduces ordering into the `rules` collection, so it may result in unexpected changes in terraform plan even if rules were not modified. This is unfortunate limitation of the `terraform-plugin-sdk` at the moment.

2022-07-20 10:42 UTC, mbojko-signalfx requested changes

2022-07-20 10:42 UTC, mbojko-signalfx commented on signalfx/resource_signalfx_detector.go
> +	tfRules := d.Get("rule").([]interface{}).List()
There is no `List()` method on an interface slice

2022-07-20 10:42 UTC, mbojko-signalfx commented on signalfx/resource_signalfx_detector.go
> +	tfRules := d.Get("rule").([]interface{}).List()
There is no `List()` method on an interface slice

2024-05-29 22:52 UTC, atoulme commented
Closing as this PR has gone stale. Please reopen and update if more work is appropriate.

2024-05-29 22:52 UTC, closed without merging